name: Build Image

on:
  push:
    branches:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.GCP_AUTH_WORKLOAD_IDENTITY_POOL }}
          service_account: ${{ vars.GCP_AUTH_SERVICE_ACCOUNT }}

      - id: build
        name: Build Docker Image
        uses: docker://us-docker.pkg.dev/deepops/pub/github-action-docker-build:1.4
        with:
          region: us
          project: deepops
          repo: pub
          name: github-action-cloudflare-pages
          accessToken: ${{ steps.auth.outputs.access_token }}
